"""Add order tracking fields

Revision ID: 6bdc029326ce
Revises: 
Create Date: 2025-05-22 00:38:10.706732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bdc029326ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('addresses_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('cart_items_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('cart_items_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('fk_parent_id', type_='foreignkey')
        batch_op.drop_constraint('comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'comments', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('order_items_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('order_items_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pickup_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipping_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipping_notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('shipping_address',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint('reactions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('reactions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expiry', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reactions_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('reactions_ibfk_2', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('shipping_address',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('shipping_notes')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('estimated_delivery')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('shipping_at')
        batch_op.drop_column('pickup_at')
        batch_op.drop_column('confirmed_at')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_ibfk_2', 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('order_items_ibfk_1', 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_parent_id', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('comments_ibfk_2', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_items_ibfk_2', 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('cart_items_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('addresses_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.create_table('ratings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='ratings_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ratings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
